image:
  file: .gitpod.Dockerfile
tasks:
  - name: Google Chrome
    command: >
      gp sync-await start &&
      sleep 10 &&
      google-chrome --no-first-run --disable-dev-shm-usage --start-maximized --load-extension=/workspace/linkedin-autoconnect-chrome-extension/dist https://www.linkedin.com/
  - name: Vite Dev Server
    init: npm ci
    command: >
      gp sync-done start &&
      npm start
ports:
  - name: NoVNC
    port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 5990
    onOpen: ignore
  - port: 6942
    onOpen: ignore
  - port: 63342
    onOpen: ignore
