name: Build
on:
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
    - name: Use Node.js lts/*
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'
    - run: npm ci
    - run: npm run build
